### ISSUE TITLE
click on photo

### ISSUE THREAD

**Issue by mcivita** [dejanstojanovic/Facebook-Album-Browser#2]
Hi, if you try to click on a photo if works... so light box opens. Then if you reclick on the same one it doesn't

**Comment by dejanstojanovic** [comment]
Image was hidden after load, issue should be resolved now, @mcivita please check with your browser cache cleared and confirm

**Comment by mcivita** [comment]
hi. still doesn't work. i cleaned cache. check :
http://www.publimedia-italia.it/liceotasso2015/photogallery.asp
Il 14/Feb/2015 18:25 "Dejan Stojanovic" <notifications@github.com> ha
scritto:

**Comment by dejanstojanovic** [comment]
It seems to be issue only with Chrome. In Firefox and IE works fine for me.
I'll check what is causing the issue in Chrome.
The image is there and loaded, it is just hidden for some reason

**Comment by mcivita** [comment]
i see the loading icon... then never image loaded... strange
Il 14/Feb/2015 19:15 "Dejan Stojanovic" <notifications@github.com> ha
scritto:

**Comment by dejanstojanovic** [comment]
Chrome does not fire loaded event for img tag is it was in browser cache. The way I did it is to hide the old loaded image and then when new one is loaded it does not trigger loaded event in Chrome.
I'm just trying the most elegant way to fix it  :)

**Comment by mcivita** [comment]
wow. Great. let me know ;)
Il 14/Feb/2015 19:28 "Dejan Stojanovic" <notifications@github.com> ha
scritto:

**Comment by dejanstojanovic** [comment]
@mcivita give it a try now. It does not look so fancy in chrome but it works. Hope I'll find the way to find better solution when I find time and make it fancy as it is in other !Chrome browsers.

**Comment by mcivita** [comment]
should i redownload and reinstall the script or did you applied changes in
your library?
Il 14/Feb/2015 19:37 "Dejan Stojanovic" <notifications@github.com> ha
scritto:

**Comment by dejanstojanovic** [comment]
Just download and replace jquery.fb.albumbrowser.js. Changes are committed to GitHub repository
Let me know if it works properly now

**Comment by mcivita** [comment]
Great, it works now. 
The only thing that doesn't show the second time that i click on the image are arrow navigation buttons, but it's ok for the moment. Thanks a lot.

**Comment by dejanstojanovic** [comment]
That issue is related to the same thing for sure. As soon as I manage to fix it, I'll close the issue and you'll get notified to pick up new code with the fix

**Comment by tnmtechnologies** [comment]
Hi,
Great plugin. 
I found some issues with safari on iOS.
When going into an album, some thumbnails are not well aligned.
If I do a rotation of the screen when displaying a picture, the loading spinner is rendered, it should not.
Thanks in advance

**Comment by dejanstojanovic** [comment]
Hi,
Thanks for pointing out the issue. 
I'll try to reproduce it and do the fix.

**Comment by tnmtechnologies** [comment]
Hi Dejan,

No problem.
I did the tests on an ipad 3/iOS 8.2. The issue also occurs on iphone 6
with an iOS 8.x versions (not 8.2).
It seems to be worth on iOS7.x.
The good news is that it can't reproduce it with google chrome, it only
occurs with safari.

If it can help.

Kind regards,

Michel

PS: Let me know if you need screenshots I could send them this evening.

2015-04-02 7:15 GMT+02:00 Dejan Stojanovic <notifications@github.com>:

**Comment by dejanstojanovic** [comment]
That would be great if you could send me screenshots since I'm not an Apple user :)

**Comment by tnmtechnologies** [comment]
Hi,

Here are 2 screenshots.

Kind regards.

![dejan2](https://cloud.githubusercontent.com/assets/11523120/6973282/eeca14fc-d989-11e4-97e8-9e9146bfca5e.png)
![dejan1](https://cloud.githubusercontent.com/assets/11523120/6973283/eecaf962-d989-11e4-966e-f87a88d26977.png)

**Comment by dejanstojanovic** [comment]
Thanks, I'm pretty sure that it is something related to css. Will have a look at it

**Comment by dejanstojanovic** [comment]
Hello, I checked-in some changes. Can you check now and let me know is it fixed?

**Comment by tnmtechnologies** [comment]
Hello,
From this URL I didn't find any change.
Looking in the CSS file jquery.fb.albumbrowser.css, I didn't find the piece of code you commented on github (from lines 42 to 44).
Regards.

**Comment by dejanstojanovic** [comment]
So you still have the layout issue on Safari?
I checked it on my daughter's iPad and seemed to work fine.

**Comment by tnmtechnologies** [comment]
Hi,
I confirm the CSS file is not up to date on http://www.jqueryscript.net/demo/jQuery-Plugin-To-Display-Facebook-Albums-Photos-On-Your-Website/src/jquery.fb.albumbrowser.css.
So I went to Plunker where the CSS file is up to date (I can see the piece of code in comment). It did a test with an iPad 3/iOS8.2 and your fix works well!
Thank you ;)

**Comment by dejanstojanovic** [comment]
Great. 
If you spot any other bug or have any idea for new useful functionality, just please open new issue here on GitHub.

Cheers
